name: Update Subscription

on:
  schedule:
    - cron: '*/1 * * * *'  # هر ۱ دقیقه
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install requests
      run: pip install requests

    - name: Run script
      run: python main.py

    - name: Commit & Push
      run: |
        git config user.name "GitHub Bot"
        git config user.email "bot@github.com"
        git add sub.txt
        git commit -m "Update subscription" || echo "No changes"
        git push
